<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '采购',
    'icon' => 'fa fa-fw fa-cc-paypal',
    'url_type' => 'module_admin',
    'url_value' => 'purchase/ask/lists',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '采购查询',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '采购申请查询',
            'icon' => 'fa fa-fw fa-share-alt',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/ask/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '采购计划查询',
            'icon' => 'fa fa-fw fa-table',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/plan/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '采购询价查询',
            'icon' => 'fa fa-fw fa-usd',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/money/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
          ],
          [
            'title' => '采购合同查询',
            'icon' => 'fa fa-fw fa-file',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/hetong/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
          ],
          [
            'title' => '采购订单查询',
            'icon' => 'fa fa-fw fa-tasks',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/order/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 5,
            'status' => 1,
          ],
          [
            'title' => '采购到货查询',
            'icon' => 'fa fa-fw fa-briefcase',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/arrival/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 6,
            'status' => 1,
          ],
          [
            'title' => '采购退货查询',
            'icon' => 'fa fa-fw fa-folder-open',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/cancel/lists',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 7,
            'status' => 0,
          ],
        ],
      ],
      [
        'title' => '采购申请',
        'icon' => 'fa fa-fw fa-share-alt',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '申请列表',
            'icon' => 'fa fa-fw fa-share-alt',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/ask/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
              [
                'title' => '查看详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加申请',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/ask/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '获取物品明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/ask/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购计划',
        'icon' => 'fa fa-fw fa-table',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 1,
        'child' => [
          [
            'title' => '计划列表',
            'icon' => 'fa fa-fw fa-table',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/plan/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加计划',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/plan/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '获取物品明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/plan/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购询价',
        'icon' => 'fa fa-fw fa-usd',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 1,
        'child' => [
          [
            'title' => '询价列表',
            'icon' => 'fa fa-fw fa-usd',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/money/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '询价详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加询价',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/money/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '物资明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/money/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购合同',
        'icon' => 'fa fa-fw fa-file',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 5,
        'status' => 1,
        'child' => [
          [
            'title' => '合同列表',
            'icon' => 'fa fa-fw fa-file',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/hetong/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加合同',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/hetong/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '物资明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/hetong/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购订单',
        'icon' => 'fa fa-fw fa-tasks',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 6,
        'status' => 1,
        'child' => [
          [
            'title' => '采购订单',
            'icon' => 'fa fa-fw fa-tasks',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/order/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加订单',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/order/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '物资明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/order/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购到货',
        'icon' => 'fa fa-fw fa-briefcase',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 7,
        'status' => 1,
        'child' => [
          [
            'title' => '采购到货',
            'icon' => 'fa fa-fw fa-briefcase',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/arrival/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '物资详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加到货',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/arrival/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '物资明细',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/arrival/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '采购退货',
        'icon' => 'fa fa-fw fa-folder-open',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 8,
        'status' => 0,
        'child' => [
          [
            'title' => '采购退货',
            'icon' => 'fa fa-fw fa-folder-open',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/cancel/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/cancel/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/cancel/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/cancel/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/cancel/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/cancel/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加退货',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/cancel/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '基本设置',
        'icon' => 'fa fa-fw fa-gear',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '采购类型',
            'icon' => 'fa fa-fw fa-gear',
            'url_type' => 'module_admin',
            'url_value' => 'purchase/type/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'purchase/type/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
