<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '库存管理',
    'icon' => 'fa fa-fw fa-home',
    'url_type' => 'module_admin',
    'url_value' => 'stock/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '基础物资库',
        'icon' => 'fa fa-fw fa-list-alt',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '物资列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/material/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '添加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '物资类型',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/material_type/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material_type/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material_type/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material_type/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '获取类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/material_type/getnestmenu',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '仓库管理',
        'icon' => 'fa fa-fw fa-book',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '仓库列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/house/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/house/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/house/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '仓库类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/house_type/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
                'child' => [
                  [
                    'title' => '添加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'stock/house_type/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 1,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'stock/house_type/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 2,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'stock/house_type/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 3,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'stock/house_type/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 4,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'stock/house_type/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 5,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '添加仓库',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/house/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '入库管理',
        'icon' => 'glyphicon glyphicon-log-in',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 1,
        'child' => [
          [
            'title' => '采购入库单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/purchase/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/purchase/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建采购入库单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/purchase/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出物品',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/purchase/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '完工入库单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/produce/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/produce/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建完工入库单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/produce/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出物品',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/produce/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '其他入库单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/otherin/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 5,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/otherin/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建其他入库单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/otherin/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 6,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/otherin/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '出库管理',
        'icon' => 'glyphicon glyphicon-log-out',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 1,
        'child' => [
          [
            'title' => '销售出库单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/sell/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/sell/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建销售出库单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/sell/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/sell/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '其他出库单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/otherout/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/otherout/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建其他出库单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/otherout/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/otherout/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '借货管理',
        'icon' => 'fa fa-fw fa-external-link',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 5,
        'status' => 1,
        'child' => [
          [
            'title' => '借货申请单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/borrow/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/borrow/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建借货申请单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/borrow/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/borrow/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '借货返还单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/restore/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/restore/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建借货返还单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/restore/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/restore/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '库存调拨',
        'icon' => 'glyphicon glyphicon-retweet',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 6,
        'status' => 1,
        'child' => [
          [
            'title' => '库存调拨单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/allot/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/allot/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建库存调拨单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/allot/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出物品列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/allot/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '期末盘点',
        'icon' => 'glyphicon glyphicon-list-alt',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 7,
        'status' => 1,
        'child' => [
          [
            'title' => '期末盘点单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/check/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/check/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建期末盘点单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/check/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/check/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '库存报损',
        'icon' => 'fa fa-fw fa-hdd-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 8,
        'status' => 1,
        'child' => [
          [
            'title' => '库存报损单列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/bad/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/bad/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新建库存报损单',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/bad/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'stock/bad/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '库存查询',
        'icon' => 'fa fa-fw fa-search',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 9,
        'status' => 0,
        'child' => [
          [
            'title' => '现有库存查询',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/stock/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '库存限量报警',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/stock/warn',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '库存流水账',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'stock/stock/flow',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '基本设置',
        'icon' => 'fa fa-fw fa-gear',
        'url_type' => 'module_admin',
        'url_value' => 'stock/index/config',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 10,
        'status' => 0,
      ],
    ],
  ],
];
