<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '施工',
    'icon' => 'fa fa-fw fa-fort-awesome',
    'url_type' => 'module_admin',
    'url_value' => 'constructionsite/log/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '施工日志',
        'icon' => 'fa fa-fw fa-file',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '日志列表',
            'icon' => 'fa fa-fw fa-file-text',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/log/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/log/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/log/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/log/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/log/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/log/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新增日志',
            'icon' => 'fa fa-fw fa-plus-square',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/log/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '设计变更',
        'icon' => 'fa fa-fw fa-share-square-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '查看变更',
            'icon' => 'fa fa-fw fa-share-square',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/change/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/change/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/change/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/change/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/change/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/change/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '发布变更',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/change/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '技术交底',
        'icon' => 'fa fa-fw fa-handshake-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 1,
        'child' => [
          [
            'title' => '查看列表',
            'icon' => 'fa fa-fw fa-handshake-o',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/tell/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/tell/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/tell/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/tell/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/tell/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/tell/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加交底',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/tell/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '施工组织方案',
        'icon' => 'fa fa-fw fa-files-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 1,
        'child' => [
          [
            'title' => '查看方案',
            'icon' => 'fa fa-fw fa-files-o',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/plan/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '查看详情',
                'icon' => 'fa fa-fw fa-search',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/plan/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/plan/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/plan/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/plan/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'constructionsite/plan/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新增方案',
            'icon' => 'fa fa-fw fa-plus-circle',
            'url_type' => 'module_admin',
            'url_value' => 'constructionsite/plan/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
    ],
  ],
];
