<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '人事',
    'icon' => 'fa fa-fw fa-vcard-o',
    'url_type' => 'module_admin',
    'url_value' => 'personnel/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '人事管理',
        'icon' => 'fa fa-fw fa-vcard',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '人事档案',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/record/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '合同管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/contract/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '续签',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/addmore',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '证件管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/papers/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '证件类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papercat/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '奖惩管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/award/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '奖惩项目',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/awardcate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '员工关怀',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/care/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '薪资管理',
        'icon' => 'fa fa-fw fa-money',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '薪资列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/wage/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '薪资设定',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资核算',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/check',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '工资核算',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '薪资类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wagecate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '修改',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '选择用户',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wage/choose',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '签到打卡',
        'icon' => 'fa fa-fw fa-edit',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '签到打卡',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/sign/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '签到详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '签到',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/sign',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '上下班打卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/work',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '打卡详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '招聘管理',
        'icon' => 'fa fa-fw fa-drivers-license-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '招聘列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/recruit/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '招聘申请',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '工作日志',
        'icon' => 'fa fa-fw fa-table',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '日志列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/daily/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '查阅',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
  [
    'title' => '人事',
    'icon' => 'fa fa-fw fa-vcard-o',
    'url_type' => 'module_admin',
    'url_value' => 'personnel/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '人事管理',
        'icon' => 'fa fa-fw fa-vcard',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '人事档案',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/record/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '合同管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/contract/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '续签',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/addmore',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '证件管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/papers/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '证件类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papercat/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],         
          [
            'title' => '奖惩管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/award/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '奖惩项目',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/awardcate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '员工关怀',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/care/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '薪资管理',
        'icon' => 'fa fa-fw fa-money',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '薪资列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/wage/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '薪资设定',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资核算',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/check',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '工资核算',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '薪资类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wagecate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '修改',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '选择用户',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wage/choose',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '签到打卡',
        'icon' => 'fa fa-fw fa-edit',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '签到打卡',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/sign/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '签到详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '签到',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/sign',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '上下班打卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/work',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '打卡详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '招聘管理',
        'icon' => 'fa fa-fw fa-drivers-license-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '招聘列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/recruit/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '招聘申请',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '工作日志',
        'icon' => 'fa fa-fw fa-table',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '日志列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/daily/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '查阅',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/daily/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
  [
    'title' => '人事',
    'icon' => 'fa fa-fw fa-vcard-o',
    'url_type' => 'module_admin',
    'url_value' => 'personnel/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '人事管理',
        'icon' => 'fa fa-fw fa-vcard',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '人事档案',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/record/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/record/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '合同管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/contract/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '续签',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/addmore',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/contract/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '证件管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/papers/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '证件类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papercat/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/papercat/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '选择用户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/papers/choose',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '人事调整',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/flow/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '奖惩管理',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/award/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/award/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '奖惩项目',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/awardcate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '启用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/enable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '禁用',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/awardcate/disable',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '员工关怀',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/care/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '执行',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '取消',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/care/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '薪资管理',
        'icon' => 'fa fa-fw fa-money',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '薪资列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/wage/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '薪资设定',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资核算',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/check',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '薪资详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '工资核算',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagelist/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '薪资类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wagecate/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '增加',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/add',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '修改',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                  [
                    'title' => '删除',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wagecate/delete',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/wage/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
                'child' => [
                  [
                    'title' => '选择用户',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'personnel/wage/choose',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 100,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '签到打卡',
        'icon' => 'fa fa-fw fa-edit',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '签到打卡',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/sign/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '签到详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/view',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '签到',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/sign',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '上下班打卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/work',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '打卡详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/sign/detail',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '招聘管理',
        'icon' => 'fa fa-fw fa-drivers-license-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '招聘列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'personnel/recruit/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '招聘申请',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'personnel/recruit/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
    ],
  ],
];
