<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '项目',
    'icon' => 'fa fa-fw fa-fighter-jet',
    'url_type' => 'module_admin',
    'url_value' => 'tender/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '项目管理',
        'icon' => 'fa fa-fw fa-th-large',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '项目列表',
            'icon' => 'fa fa-fw fa-th-list',
            'url_type' => 'module_admin',
            'url_value' => 'tender/index/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/index/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除投标',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/index/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '项目详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/index/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新增项目',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module_admin',
            'url_value' => 'tender/index/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '项目类型管理',
        'icon' => 'fa fa-fw fa-th-large',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '项目类型列表',
            'icon' => 'fa fa-fw fa-book',
            'url_type' => 'module_admin',
            'url_value' => 'tender/type/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑项目类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/type/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除项目类型',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/type/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新增项目类型',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module_admin',
            'url_value' => 'tender/type/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '招标文件管理',
        'icon' => 'fa fa-fw fa-th-large',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 0,
        'child' => [
          [
            'title' => '招投标文件购买申请列表',
            'icon' => 'fa fa-fw fa-file-text-o',
            'url_type' => 'module_admin',
            'url_value' => 'tender/plan/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑申请',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/plan/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/plan/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '查看详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/plan/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '添加申请',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module_admin',
            'url_value' => 'tender/plan/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '投标保证金管理',
        'icon' => 'fa fa-fw fa-hashtag',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 0,
        'child' => [
          [
            'title' => '投标保证金列表',
            'icon' => 'fa fa-fw fa-th',
            'url_type' => 'module_admin',
            'url_value' => 'tender/margin/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/margin/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/margin/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/margin/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '投标保证金申请',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module_admin',
            'url_value' => 'tender/margin/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '材料需用计划',
        'icon' => 'fa fa-fw fa-building-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 5,
        'status' => 1,
        'child' => [
          [
            'title' => '计划列表',
            'icon' => 'fa fa-fw fa-th-list',
            'url_type' => 'module_admin',
            'url_value' => 'tender/materials/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/materials/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/materials/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '新增计划',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module_admin',
            'url_value' => 'tender/materials/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/materials/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '租赁管理',
        'icon' => 'fa fa-fw fa-user-circle-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 6,
        'status' => 1,
        'child' => [
          [
            'title' => '租赁计划',
            'icon' => 'fa fa-fw fa-folder',
            'url_type' => 'module_admin',
            'url_value' => 'tender/hire/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '弹出',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/choose_materials',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '租赁管理查询',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'tender/hire/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '查看',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/hire/task_list',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '项目利润',
        'icon' => 'fa fa-fw fa-yen',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 7,
        'status' => 1,
        'child' => [
          [
            'title' => '项目利润',
            'icon' => 'fa fa-fw fa-cny',
            'url_type' => 'module_admin',
            'url_value' => 'tender/profit/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '项目总成本统计表',
            'icon' => 'fa fa-fw fa-map',
            'url_type' => 'module_admin',
            'url_value' => 'tender/costall/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '项目利润表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/costall/show',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '返回',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tender/costall/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '项目间接费用报表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'tender/other/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
    ],
  ],
];
