<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 模块信息
 */
return [
  'name' => 'personnel',
  'title' => '人事',
  'identifier' => 'personnel.dong.module',
  'icon' => 'fa fa-fw fa-vcard-o',
  'description' => '人事模块',
  'author' => 'HuangYuanDong',
  'author_url' => '',
  'version' => '1.0.0',
  'need_module' => [
    [
      'admin',
      'admin.dolphinphp.module',
      '1.0.0',
    ],
  ],
  'need_plugin' => [],
  'tables' => [
    'personnel_award',
    'personnel_awardcate',
    'personnel_care',
    'personnel_column',
    'personnel_contract',
    'personnel_daily',
    'personnel_plan',
    'personnel_papercat',
    'personnel_papers',
    'personnel_record',
    'personnel_recruit',
    'personnel_sign',
    'personnel_wage',
    'personnel_wagecate',
    'personnel_wagelist',
    'personnel_work',
  ],
  'database_prefix' => 'dp_',
  'config' => [
    [
      'radio',
      'filter_var',
      '打卡网络',
      '',
      [
        '互联网',
        '局域网',
      ],
      '0',
    ],
  ],
  'action' => [
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_delete',
      'title' => '删除证件',
      'remark' => '删除证件',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_add',
      'title' => '添加证件',
      'remark' => '添加证件',
      'rule' => '',
      'log' => '[user|get_nickname] 添加证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_edit',
      'title' => '编辑证件',
      'remark' => '编辑证件',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_disable',
      'title' => '禁用证件类型',
      'remark' => '禁用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_enable',
      'title' => '启用证件类型',
      'remark' => '启用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_delete',
      'title' => '删除证件类型',
      'remark' => '删除证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_edit',
      'title' => '编辑证件类型',
      'remark' => '编辑证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_add',
      'title' => '新增证件类型',
      'remark' => '新增证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 新增证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_edit',
      'title' => '编辑日志',
      'remark' => '编辑日志',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_delete',
      'title' => '删除日志',
      'remark' => '删除日志',
      'rule' => '',
      'log' => '[user|get_nickname] 删除日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_add',
      'title' => '添加日志',
      'remark' => '添加日志',
      'rule' => '',
      'log' => '[user|get_nickname] 添加日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_delete',
      'title' => '删除合同',
      'remark' => '删除合同',
      'rule' => '',
      'log' => '[user|get_nickname] 删除合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_edit',
      'title' => '编辑合同',
      'remark' => '编辑合同',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_add',
      'title' => '添加合同',
      'remark' => '添加合同',
      'rule' => '',
      'log' => '[user|get_nickname] 添加合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_delete',
      'title' => '删除关怀',
      'remark' => '删除关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 删除关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_edit',
      'title' => '编辑关怀',
      'remark' => '编辑关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_add',
      'title' => '新增关怀',
      'remark' => '新增关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 新增关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_disable',
      'title' => '禁用奖惩类型',
      'remark' => '禁用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_enable',
      'title' => '启用奖惩类型',
      'remark' => '启用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_delete',
      'title' => '删除奖惩类型',
      'remark' => '删除奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_edit',
      'title' => '编辑奖惩类型',
      'remark' => '编辑奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_add',
      'title' => '增加奖惩类型',
      'remark' => '增加奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 增加奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_delete',
      'title' => '删除奖惩',
      'remark' => '删除奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_edit',
      'title' => '编辑奖惩',
      'remark' => '编辑奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_add',
      'title' => '新增奖惩',
      'remark' => '新增奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 新增奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_edit',
      'title' => '修改核算工资',
      'remark' => '修改核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 修改核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_add',
      'title' => '核算工资',
      'remark' => '核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_disable',
      'title' => '禁用薪资类型',
      'remark' => '禁用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_enable',
      'title' => '启用薪资类型',
      'remark' => '启用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_edit',
      'title' => '编辑薪资类型',
      'remark' => '编辑薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_edit',
      'title' => '编辑薪资标准',
      'remark' => '编辑薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_add',
      'title' => '添加薪资标准',
      'remark' => '添加薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_delete',
      'title' => '删除招聘',
      'remark' => '删除招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 删除招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_edit',
      'title' => '编辑招聘',
      'remark' => '编辑招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_edit',
      'title' => '编辑人事档案',
      'remark' => '编辑人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_add',
      'title' => '新增人事档案',
      'remark' => '新增人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 新增人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_delete',
      'title' => '删除证件',
      'remark' => '删除证件',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_edit',
      'title' => '编辑证件',
      'remark' => '编辑证件',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_add',
      'title' => '添加证件',
      'remark' => '添加证件',
      'rule' => '',
      'log' => '[user|get_nickname] 添加证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_disable',
      'title' => '禁用证件类型',
      'remark' => '禁用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_enable',
      'title' => '启用证件类型',
      'remark' => '启用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_delete',
      'title' => '删除证件类型',
      'remark' => '删除证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_edit',
      'title' => '编辑证件类型',
      'remark' => '编辑证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_add',
      'title' => '新增证件类型',
      'remark' => '新增证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 新增证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_plan_delete',
      'title' => '删除计划',
      'remark' => '删除计划',
      'rule' => '',
      'log' => '[user|get_nickname] 删除计划：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_plan_edit',
      'title' => '编辑计划',
      'remark' => '编辑计划',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑计划：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_plan_add',
      'title' => '添加计划',
      'remark' => '添加计划',
      'rule' => '',
      'log' => '[user|get_nickname] 添加计划：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_delete',
      'title' => '删除日志',
      'remark' => '删除日志',
      'rule' => '',
      'log' => '[user|get_nickname] 删除日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_edit',
      'title' => '编辑日志',
      'remark' => '编辑日志',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_add',
      'title' => '添加日志',
      'remark' => '添加日志',
      'rule' => '',
      'log' => '[user|get_nickname] 添加日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_delete',
      'title' => '删除合同',
      'remark' => '删除合同',
      'rule' => '',
      'log' => '[user|get_nickname] 删除合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_edit',
      'title' => '编辑合同',
      'remark' => '编辑合同',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_add',
      'title' => '添加合同',
      'remark' => '添加合同',
      'rule' => '',
      'log' => '[user|get_nickname] 添加合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_delete',
      'title' => '删除关怀',
      'remark' => '删除关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 删除关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_edit',
      'title' => '编辑关怀',
      'remark' => '编辑关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_add',
      'title' => '新增关怀',
      'remark' => '新增关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 新增关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_disable',
      'title' => '禁用奖惩类型',
      'remark' => '禁用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_enable',
      'title' => '启用奖惩类型',
      'remark' => '启用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_delete',
      'title' => '删除奖惩类型',
      'remark' => '删除奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_edit',
      'title' => '编辑奖惩类型',
      'remark' => '编辑奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_add',
      'title' => '增加奖惩类型',
      'remark' => '增加奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 增加奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_delete',
      'title' => '删除奖惩',
      'remark' => '删除奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_edit',
      'title' => '编辑奖惩',
      'remark' => '编辑奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_add',
      'title' => '新增奖惩',
      'remark' => '新增奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 新增奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_edit',
      'title' => '修改核算工资',
      'remark' => '修改核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 修改核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_add',
      'title' => '核算工资',
      'remark' => '核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_disable',
      'title' => '禁用薪资类型',
      'remark' => '禁用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_enable',
      'title' => '启用薪资类型',
      'remark' => '启用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_edit',
      'title' => '编辑薪资类型',
      'remark' => '编辑薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_add',
      'title' => '新增奖惩',
      'remark' => '新增奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 新增奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_edit',
      'title' => '编辑奖惩',
      'remark' => '编辑奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_delete',
      'title' => '删除奖惩',
      'remark' => '删除奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_add',
      'title' => '增加奖惩类型',
      'remark' => '增加奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 增加奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_edit',
      'title' => '编辑奖惩类型',
      'remark' => '编辑奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_delete',
      'title' => '删除奖惩类型',
      'remark' => '删除奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_enable',
      'title' => '启用奖惩类型',
      'remark' => '启用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_awardcate_disable',
      'title' => '禁用奖惩类型',
      'remark' => '禁用奖惩类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用奖惩类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_add',
      'title' => '新增关怀',
      'remark' => '新增关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 新增关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_edit',
      'title' => '编辑关怀',
      'remark' => '编辑关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_care_delete',
      'title' => '删除关怀',
      'remark' => '删除关怀',
      'rule' => '',
      'log' => '[user|get_nickname] 删除关怀：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_add',
      'title' => '添加合同',
      'remark' => '添加合同',
      'rule' => '',
      'log' => '[user|get_nickname] 添加合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_edit',
      'title' => '编辑合同',
      'remark' => '编辑合同',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_contract_delete',
      'title' => '删除合同',
      'remark' => '删除合同',
      'rule' => '',
      'log' => '[user|get_nickname] 删除合同：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_add',
      'title' => '添加日志',
      'remark' => '添加日志',
      'rule' => '',
      'log' => '[user|get_nickname] 添加日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_edit',
      'title' => '编辑日志',
      'remark' => '编辑日志',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_daily_delete',
      'title' => '删除日志',
      'remark' => '删除日志',
      'rule' => '',
      'log' => '[user|get_nickname] 删除日志：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_add',
      'title' => '新增证件类型',
      'remark' => '新增证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 新增证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_edit',
      'title' => '编辑证件类型',
      'remark' => '编辑证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_delete',
      'title' => '删除证件类型',
      'remark' => '删除证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_enable',
      'title' => '启用证件类型',
      'remark' => '启用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papercat_disable',
      'title' => '禁用证件类型',
      'remark' => '禁用证件类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用证件类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_add',
      'title' => '添加证件',
      'remark' => '添加证件',
      'rule' => '',
      'log' => '[user|get_nickname] 添加证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_edit',
      'title' => '编辑证件',
      'remark' => '编辑证件',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_papers_delete',
      'title' => '删除证件',
      'remark' => '删除证件',
      'rule' => '',
      'log' => '[user|get_nickname] 删除证件：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_add',
      'title' => '新增人事档案',
      'remark' => '新增人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 新增人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_edit',
      'title' => '编辑人事档案',
      'remark' => '编辑人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_edit',
      'title' => '编辑招聘',
      'remark' => '编辑招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_delete',
      'title' => '删除招聘',
      'remark' => '删除招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 删除招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_add',
      'title' => '添加薪资标准',
      'remark' => '添加薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_edit',
      'title' => '编辑薪资标准',
      'remark' => '编辑薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_add',
      'title' => '新增人事档案',
      'remark' => '新增人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 新增人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_record_edit',
      'title' => '编辑人事档案',
      'remark' => '编辑人事档案',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑人事档案：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_add',
      'title' => '新增招聘',
      'remark' => '新增招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 新增招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_edit',
      'title' => '编辑招聘',
      'remark' => '编辑招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_recruit_delete',
      'title' => '删除招聘',
      'remark' => '删除招聘',
      'rule' => '',
      'log' => '[user|get_nickname] 删除招聘：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_add',
      'title' => '添加薪资标准',
      'remark' => '添加薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wage_edit',
      'title' => '编辑薪资标准',
      'remark' => '编辑薪资标准',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资标准：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_add',
      'title' => '添加薪资类型',
      'remark' => '添加薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 添加薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_edit',
      'title' => '编辑薪资类型',
      'remark' => '编辑薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 编辑薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_enable',
      'title' => '启用薪资类型',
      'remark' => '启用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 启用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagecate_disable',
      'title' => '禁用薪资类型',
      'remark' => '禁用薪资类型',
      'rule' => '',
      'log' => '[user|get_nickname] 禁用薪资类型：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_add',
      'title' => '核算工资',
      'remark' => '核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_wagelist_edit',
      'title' => '修改核算工资',
      'remark' => '修改核算工资',
      'rule' => '',
      'log' => '[user|get_nickname] 修改核算工资：[details]',
      'status' => 1,
    ],
    [
      'module' => 'personnel',
      'name' => 'personnel_award_add',
      'title' => '新增奖惩',
      'remark' => '新增奖惩',
      'rule' => '',
      'log' => '[user|get_nickname] 新增奖惩：[details]',
      'status' => 1,
    ],
  ],
  'access' => [
    'group' => [
      'tab_title' => '人事授权',
      'table_name' => 'personnel_column',
      'primary_key' => 'id',
      'parent_id' => 'pid',
      'node_name' => 'name',
    ],
  ],
];
